<?php
namespace docGenerator;
use webfiori\framework\router\Router;
class DocGeneratorRoutes{
    public static function createRoutes(){
        Router::view([
            'path'=>'docs/webfiori/WebFiori',
            'route-to'=>'/apis/webfiori/WebFioriView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori',
            'route-to'=>'/apis/webfiori/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/logic/ConfigController',
            'route-to'=>'/apis/webfiori/logic/ConfigControllerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/logic',
            'route-to'=>'/apis/webfiori/logic/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/logic/Controller',
            'route-to'=>'/apis/webfiori/logic/ControllerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/logic/EmailController',
            'route-to'=>'/apis/webfiori/logic/EmailControllerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/logic/WebsiteController',
            'route-to'=>'/apis/webfiori/logic/WebsiteControllerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/ini/InitAutoLoad',
            'route-to'=>'/apis/webfiori/ini/InitAutoLoadView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/ini',
            'route-to'=>'/apis/webfiori/ini/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/ini/InitCliCommands',
            'route-to'=>'/apis/webfiori/ini/InitCliCommandsView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/ini/InitCron',
            'route-to'=>'/apis/webfiori/ini/InitCronView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/ini/InitPrivileges',
            'route-to'=>'/apis/webfiori/ini/InitPrivilegesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Access',
            'route-to'=>'/apis/webfiori/entity/AccessView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity',
            'route-to'=>'/apis/webfiori/entity/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/AutoLoader',
            'route-to'=>'/apis/webfiori/entity/AutoLoaderView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/DBConnectionFactory',
            'route-to'=>'/apis/webfiori/entity/DBConnectionFactoryView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/DBConnectionInfo',
            'route-to'=>'/apis/webfiori/entity/DBConnectionInfoView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/DatabaseSchema',
            'route-to'=>'/apis/webfiori/entity/DatabaseSchemaView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ExtendedWebServices',
            'route-to'=>'/apis/webfiori/entity/ExtendedWebServicesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/File',
            'route-to'=>'/apis/webfiori/entity/FileView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/FileHandler',
            'route-to'=>'/apis/webfiori/entity/FileHandlerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Logger',
            'route-to'=>'/apis/webfiori/entity/LoggerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Page',
            'route-to'=>'/apis/webfiori/entity/PageView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Privilege',
            'route-to'=>'/apis/webfiori/entity/PrivilegeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/PrivilegesGroup',
            'route-to'=>'/apis/webfiori/entity/PrivilegesGroupView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/SessionManager',
            'route-to'=>'/apis/webfiori/entity/SessionManagerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Theme',
            'route-to'=>'/apis/webfiori/entity/ThemeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Uploader',
            'route-to'=>'/apis/webfiori/entity/UploaderView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/User',
            'route-to'=>'/apis/webfiori/entity/UserView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/Util',
            'route-to'=>'/apis/webfiori/entity/UtilView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui/ErrorBox',
            'route-to'=>'/apis/webfiori/entity/ui/ErrorBoxView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui',
            'route-to'=>'/apis/webfiori/entity/ui/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui/MessageBox',
            'route-to'=>'/apis/webfiori/entity/ui/MessageBoxView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui/NotFoundView',
            'route-to'=>'/apis/webfiori/entity/ui/NotFoundViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui/ServerErrView',
            'route-to'=>'/apis/webfiori/entity/ui/ServerErrViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/ui/ServiceUnavailableView',
            'route-to'=>'/apis/webfiori/entity/ui/ServiceUnavailableViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/APIRoutes',
            'route-to'=>'/apis/webfiori/entity/router/APIRoutesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router',
            'route-to'=>'/apis/webfiori/entity/router/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/ClosureRoutes',
            'route-to'=>'/apis/webfiori/entity/router/ClosureRoutesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/OtherRoutes',
            'route-to'=>'/apis/webfiori/entity/router/OtherRoutesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/Router',
            'route-to'=>'/apis/webfiori/entity/router/RouterView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/RouterUri',
            'route-to'=>'/apis/webfiori/entity/router/RouterUriView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/router/ViewRoutes',
            'route-to'=>'/apis/webfiori/entity/router/ViewRoutesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/restEasy/APIAction',
            'route-to'=>'/apis/restEasy/APIActionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/restEasy',
            'route-to'=>'/apis/restEasy/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/restEasy/APIFilter',
            'route-to'=>'/apis/restEasy/APIFilterView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/restEasy/RequestParameter',
            'route-to'=>'/apis/restEasy/RequestParameterView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/restEasy/WebServices',
            'route-to'=>'/apis/restEasy/WebServicesView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/Comparable',
            'route-to'=>'/apis/phpStructs/ComparableView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs',
            'route-to'=>'/apis/phpStructs/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/DataStruct',
            'route-to'=>'/apis/phpStructs/DataStructView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/LinkedList',
            'route-to'=>'/apis/phpStructs/LinkedListView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/Node',
            'route-to'=>'/apis/phpStructs/NodeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/Queue',
            'route-to'=>'/apis/phpStructs/QueueView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/Stack',
            'route-to'=>'/apis/phpStructs/StackView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/Anchor',
            'route-to'=>'/apis/phpStructs/html/AnchorView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html',
            'route-to'=>'/apis/phpStructs/html/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/Br',
            'route-to'=>'/apis/phpStructs/html/BrView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/CodeSnippet',
            'route-to'=>'/apis/phpStructs/html/CodeSnippetView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/HTMLDoc',
            'route-to'=>'/apis/phpStructs/html/HTMLDocView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/HTMLList',
            'route-to'=>'/apis/phpStructs/html/HTMLListView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/HTMLNode',
            'route-to'=>'/apis/phpStructs/html/HTMLNodeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/HeadNode',
            'route-to'=>'/apis/phpStructs/html/HeadNodeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/Input',
            'route-to'=>'/apis/phpStructs/html/InputView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/InvalidNodeNameException',
            'route-to'=>'/apis/phpStructs/html/InvalidNodeNameExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/JsCode',
            'route-to'=>'/apis/phpStructs/html/JsCodeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/Label',
            'route-to'=>'/apis/phpStructs/html/LabelView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/ListItem',
            'route-to'=>'/apis/phpStructs/html/ListItemView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/OrderedList',
            'route-to'=>'/apis/phpStructs/html/OrderedListView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/PNode',
            'route-to'=>'/apis/phpStructs/html/PNodeView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/TableCell',
            'route-to'=>'/apis/phpStructs/html/TableCellView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/TableRow',
            'route-to'=>'/apis/phpStructs/html/TableRowView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phpStructs/html/UnorderedList',
            'route-to'=>'/apis/phpStructs/html/UnorderedListView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/EntityMapper',
            'route-to'=>'/apis/phMysql/EntityMapperView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql',
            'route-to'=>'/apis/phMysql/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/ForeignKey',
            'route-to'=>'/apis/phMysql/ForeignKeyView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/JoinTable',
            'route-to'=>'/apis/phMysql/JoinTableView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/MySQLColumn',
            'route-to'=>'/apis/phMysql/MySQLColumnView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/MySQLLink',
            'route-to'=>'/apis/phMysql/MySQLLinkView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/MySQLQuery',
            'route-to'=>'/apis/phMysql/MySQLQueryView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/phMysql/MySQLTable',
            'route-to'=>'/apis/phMysql/MySQLTableView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/mail/EmailMessage',
            'route-to'=>'/apis/webfiori/entity/mail/EmailMessageView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/mail',
            'route-to'=>'/apis/webfiori/entity/mail/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/mail/SMTPAccount',
            'route-to'=>'/apis/webfiori/entity/mail/SMTPAccountView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/mail/SocketMailer',
            'route-to'=>'/apis/webfiori/entity/mail/SocketMailerView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/langs/Language',
            'route-to'=>'/apis/webfiori/entity/langs/LanguageView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/langs',
            'route-to'=>'/apis/webfiori/entity/langs/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/langs/LanguageAR',
            'route-to'=>'/apis/webfiori/entity/langs/LanguageARView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/langs/LanguageEN',
            'route-to'=>'/apis/webfiori/entity/langs/LanguageENView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/jsonx/JsonI',
            'route-to'=>'/apis/jsonx/JsonIView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/jsonx',
            'route-to'=>'/apis/jsonx/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/jsonx/JsonX',
            'route-to'=>'/apis/jsonx/JsonXView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/ClassLoaderException',
            'route-to'=>'/apis/webfiori/entity/exceptions/ClassLoaderExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions',
            'route-to'=>'/apis/webfiori/entity/exceptions/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/FileException',
            'route-to'=>'/apis/webfiori/entity/exceptions/FileExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/InitializationException',
            'route-to'=>'/apis/webfiori/entity/exceptions/InitializationExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/InvalidCRONExprException',
            'route-to'=>'/apis/webfiori/entity/exceptions/InvalidCRONExprExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/MissingLangException',
            'route-to'=>'/apis/webfiori/entity/exceptions/MissingLangExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/NoSuchThemeException',
            'route-to'=>'/apis/webfiori/entity/exceptions/NoSuchThemeExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/RoutingException',
            'route-to'=>'/apis/webfiori/entity/exceptions/RoutingExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/SMTPException',
            'route-to'=>'/apis/webfiori/entity/exceptions/SMTPExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/exceptions/SessionException',
            'route-to'=>'/apis/webfiori/entity/exceptions/SessionExceptionView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/AbstractJob',
            'route-to'=>'/apis/webfiori/entity/cron/AbstractJobView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron',
            'route-to'=>'/apis/webfiori/entity/cron/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/Cron',
            'route-to'=>'/apis/webfiori/entity/cron/CronView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronAPIs',
            'route-to'=>'/apis/webfiori/entity/cron/CronAPIsView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronEmail',
            'route-to'=>'/apis/webfiori/entity/cron/CronEmailView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronJob',
            'route-to'=>'/apis/webfiori/entity/cron/CronJobView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronLoginView',
            'route-to'=>'/apis/webfiori/entity/cron/CronLoginViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronTaskView',
            'route-to'=>'/apis/webfiori/entity/cron/CronTaskViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronTasksView',
            'route-to'=>'/apis/webfiori/entity/cron/CronTasksViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cron/CronView',
            'route-to'=>'/apis/webfiori/entity/cron/CronViewView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/CLI',
            'route-to'=>'/apis/webfiori/entity/cli/CLIView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli',
            'route-to'=>'/apis/webfiori/entity/cli/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/CLICommand',
            'route-to'=>'/apis/webfiori/entity/cli/CLICommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/CronCommand',
            'route-to'=>'/apis/webfiori/entity/cli/CronCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/HelpCommand',
            'route-to'=>'/apis/webfiori/entity/cli/HelpCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/ListCronCommand',
            'route-to'=>'/apis/webfiori/entity/cli/ListCronCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/ListRoutesCommand',
            'route-to'=>'/apis/webfiori/entity/cli/ListRoutesCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/ListThemesCommand',
            'route-to'=>'/apis/webfiori/entity/cli/ListThemesCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/SettingsCommand',
            'route-to'=>'/apis/webfiori/entity/cli/SettingsCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/TestRouteCommand',
            'route-to'=>'/apis/webfiori/entity/cli/TestRouteCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/entity/cli/VersionCommand',
            'route-to'=>'/apis/webfiori/entity/cli/VersionCommandView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/conf/Config',
            'route-to'=>'/apis/webfiori/conf/ConfigView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/conf',
            'route-to'=>'/apis/webfiori/conf/NSIndexView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/conf/MailConfig',
            'route-to'=>'/apis/webfiori/conf/MailConfigView.php',
            'in-sitemap'=>true
        ]);
        Router::view([
            'path'=>'docs/webfiori/conf/SiteConfig',
            'route-to'=>'/apis/webfiori/conf/SiteConfigView.php',
            'in-sitemap'=>true
        ]);
    }
}